<?php

namespace App\Models;

class Category extends Model
{

	use \Spatie\Tags\HasTags;
	/**
	 * The attributes that are mass assignable.
	 *
	 * @var list<string>
	 */
	protected $fillable = [
		'name',
	];

	protected $hidden = [
		'created_at',
		'updated_at'
	];

	public function toArray() {
		$aReturn = parent::toArray(); // TODO: Change the autogenerated stub
		$aReturn['tags'] = $this->tags->all();
		return $aReturn;
	}
}
