<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;

use Illuminate\Database\Eloquent\Relations\HasMany;
class Person extends Model
{
    /** @use HasFactory<\Database\Factories\PersonFactory> */
    use HasFactory;

	use \Spatie\Tags\HasTags;

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var list<string>
	 */
	protected $fillable = [
		'fio',
		'firstname',
		'surname',
		'lastname',
		'category_id',
		'birthday',
		'position',
		'city',
		'address',
		'description'
	];

	protected $hidden = [
	//	'id',
		'created_at',
		'updated_at'
	];

	/**
	 * Таблица БД, ассоциированная с моделью.
	 *
	 * @var string
	 */
	protected $table = 'persons';

	/**
	 * Get the comments for the blog post.
	 */
	public function projects(): HasMany
	{
		return $this->hasMany(Project::class);
	}


	public function toArray() {
		$aReturn = parent::toArray(); // TODO: Change the autogenerated stub
		$aReturn['tags'] = $this->tags->all();
		return $aReturn;
	}

	public function fill(array $attributes) {

		return parent::fill($attributes); // TODO: Change the autogenerated stub
	}
}


