<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;

class Project extends Model
{
    /** @use HasFactory<\Database\Factories\ProjectFactory> */
	use HasFactory;

	use \Spatie\Tags\HasTags;

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var list<string>
	 */
	protected $fillable = [
		'name',
		'startdate',
		'enddate',
		'description',
		'position'
	];

	protected $hidden = [
		'created_at',
		'updated_at'
	];

	/**
	 * Get the person that owns the project.
	 */
	public function person(): BelongsTo
	{
		return $this->belongsTo(Person::class);
	}

	public function toArray() {
		$aReturn = parent::toArray(); // TODO: Change the autogenerated stub
		$aReturn['tags'] = $this->tags->all();
		return $aReturn;
	}
}
